### ISSUE TITLE
Artık çalışmıyor.

### ISSUE THREAD

**Issue by theberkmusic** [tingirifistik/Enough-Reborn#1]
Eskiden 200 mesaj gönderirdim bunlardan en az 150 tanesi gelirdi. Bugün itibari ile gelmiyor. [18.02.2023]

**Comment by tingirifistik** [comment]
Bazı api ler ölmüş ama 40-45 tanesi çalışır durumda şu an.

**Comment by theberkmusic** [comment]
> Bazı api ler ölmüş ama 40-45 tanesi çalışır durumda şu an.

Peki ne zaman düzeltirsin? Türkiye'de bulunan en iyi sms bomber'a sahiptin. Acil lazım oluyor ben ve ekibime. Düzeltme ihtimalin var mı? Haber bekliyoruz. Discord'tan ekledim ghost ismim. En yakın zamanda düzeltirsin umarım.

**Comment by tingirifistik** [comment]
Bu zamanlarda düzeltmem biraz zor ama haziranda büyük bir güncelleme yapacağım.

**Comment by theberkmusic** [comment]
> Bu zamanlarda düzeltmem biraz zor ama haziranda büyük bir güncelleme yapacağım.

Tamamdır bekliyor olacağız. Çok teşekkür ederiz.

**Comment by tingirifistikfan** [comment]
> Bu zamanlarda düzeltmem biraz zor ama haziranda büyük bir güncelleme yapacağım.

of haziran ne reis

**Comment by theberkmusic** [comment]
> > Bu zamanlarda düzeltmem biraz zor ama haziranda büyük bir güncelleme yapacağım.
> 
> of haziran ne reis 

Harbiden. Bende biraz hayal kırıklığına uğradım ama saygı duymak gerek. Hiç olmayadabilirdi... Her ne kadar ihtiyacımız olsa da beklemek zorundayız. Belki nir ihtimal de olsa hızlandırabilir süreci. @tingirifistik sizce ?

**Comment by larinspub** [comment]
uygulama açılmıyor bile

**Comment by 0NAHO0** [comment]
bro bu aracı indirdiğimde içinde sadece readmi.md diye bi dosya vardı öbürkü py dosyaları nerde

**Comment by tingirifistik** [comment]
yayınlandı.
