### ISSUE TITLE
Çoğu çalışmıyor

### ISSUE THREAD

**Issue by Candeniz92** [tingirifistik/Enough-Reborn#10]
Merhaba, çoğu site çalışmıyor ve kısa bir süre sonra kendiliğinden duruyor yenilenmesi mi gerekiyor

**Comment by sms717382** [comment]
@tingirifistikfan hocam AIdan yardım alarak nasıl api çıkartıyorsunuz iletişim verebilir misiniz, teşekkürler

**Comment by sms717382** [comment]
@tingirifistik nasıl kodladığını vs. ögrettigin bir video yapsan super olur

**Comment by TTL-Klautys** [comment]
> bazi apilerin guncellenmesi gerekiyo

bir şey sorucam bu tool da sms:49 yazıyo ya o limit sınırı mı

**Comment by tingirifistikfan** [comment]
gücelledim ben dc: besevler

**Comment by tingirifistik** [comment]
@TTL-Klautys  kac farkli sms servisi oldugunu belirtiyor
