### ISSUE TITLE
Sms bomber

### ISSUE THREAD

**Issue by saris010134** [tingirifistik/Enough-Reborn#15]
Arkadaşa şaka yapmak için termux ile verdiğin kodları yazdım ve gayet güzel bi şekilde çalıştı ama bi sorun var mesajlar durmuyor durdurmam için yardımcı olurmusun rica etsem 2 gündür mesajlar durmuyor

**Comment by tingirifistik** [comment]
turbo modunda cok uzun sure calistirdiysan istekler birikmistir. Bir dahaki gonderiminde normal modu kullan

**Comment by Akrepjitem** [comment]
Durdurmak için ne yapmalıyım termuxdan mobilden
