### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Kanjoozoku** [tingirifistik/Enough-Reborn#19]
Sayın hocam Enough-Reborn için guncellemelerinizi sabirsizlikla bekliyorum müsait olursaniz bi kahve ısmarlamakta isterim

**Comment by tingirifistik** [comment]
Yazin guncelleme yapacagim. 
Insallah..

**Comment by Kanjoozoku** [comment]
Sevilmiyorsunuz hocam saygılar.

18 May 2024 Cmt 15:20 tarihinde tingirifistik ***@***.***>
şunu yazdı:

**Comment by tingirifistik** [comment]
> Sevilmiyorsunuz 

üzdü :)

**Comment by Kanjoozoku** [comment]
Şaka şaka hocam gül diye 😂😂😂❤️

18 May 2024 Cmt 17:26 tarihinde tingirifistik ***@***.***>
şunu yazdı:
