### ISSUE TITLE
Discord Botta Sorun (ACİL)

### ISSUE THREAD

**Issue by akbaba3141** [tingirifistik/Enough-Reborn#7]
discord-enough.py ye tokeni mi girdim, birlikte aç diyip python ile aç diyorum ve ImportError cannot import name 'SendSms' from 'sms' hatasını alıyorum, from sms import SendSms i kodlardan kaldırıyorum (4. satır) bu sefer açılıyor bot fakat sms göndermiyor, yardımcı olursanız sevinirim.

**Comment by graoxd** [comment]
aynı sorun bende de var dostum @tingirifistik yardımcı olursan seviniriz

**Comment by tingirifistik** [comment]
sms.py dosyasini bot klasorunun icine attiniz. ya da bot dosyasini bir ust dizine kopyalayin

**Comment by akbaba3141** [comment]
> sms.py dosyasını bot klasorunun içine attınız. ya da bot dosyasının bir ust dizine kopyalanması

@tingirifistik 
**https://streamable.com/swjscq**

**Comment by tingirifistik** [comment]
sms.py dosyasini bot klasorunun icine atmamissin
