### ISSUE TITLE
Call

### ISSUE THREAD

**Issue by tingirifistikfan** [tingirifistik/Enough-Reborn#8]
Call gelir mi. Bu arada helal olsun umarım eskisi gibi aktif şekilde güncelleme alır, başarılar

**Comment by tingirifistik** [comment]
Türkiye'de doğrulama için arama yapan servis çok az. Bulabilirsem eklerim.

**Comment by tingirifistikfan** [comment]
Yks nasıl geçti bu arada?

**Comment by tingirifistik** [comment]
mezun :/
